### ISSUE TITLE
Couldn't connect to **********: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond *****************

### ISSUE THREAD

**Issue by GopalJT** [flipbit/whois#3]
I added whois reference in my project and it is working good in local pc but when I upload project on server then it showing error : 

"Couldn't connect to whois.verisign-grs.com: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 199.7.54.74:43"

**Comment by flipbit** [comment]
Timeout issues can be caused by rate limits on WHOIS servers.  You can confirm this by attempting to download from a different IP address.

If so, slow down data requests and add caching to your application to reduce the volume of requests needed.
