### ISSUE TITLE
can't search for .site name

### ISSUE THREAD

**Issue by fventurini** [flipbit/whois#4]
Message	"WHOIS server lookup failed for blabla.site: Host sconosciuto"	string

**		StackTrace	"   in Whois.WhoisServerLookup.Lookup(String domain) in c:\\Users\\Chris\\Dropbox\\source\\whois\\Whois\\WhoisServerLookup.cs:riga 87\r\n   in Whois.Visitors.WhoisServerVisitor.Visit(WhoisRecord record) in c:\\Users\\Chris\\Dropbox\\source\\whois\\Whois\\Visitors\\WhoisServerVisitor.cs:riga 50\r\n   in Whois.WhoisLookup.Lookup(String domain) in c:\\Users\\Chris\\Dropbox\\source\\whois\\Whois\\WhoisLookup.cs:riga 84\r\n   in whois.Program.Main(String[] args) in c:\\users\\effev\\documents\\visual studio 2017\\Projects\\whois\\whois\\Program.cs:riga 26"	string
**

Please help

**Comment by flipbit** [comment]
Version 2.0.0 correctly looks up `.site` domain names.
