### ISSUE TITLE
'WhoisResponse' does not contain a definition for 'ParsedResponse'

### ISSUE THREAD

**Issue by SimonFletcher** [flipbit/whois#60]
Hi,

Apologies if this is a daft question, but when I try to compile the following:
`var json = JsonConvert.SerializeObject(response.ParsedResponse, Formatting.Indented);`

I get an error message saying that "'WhoisResponse' does not contain a definition for 'ParsedResponse'".  Am I missing a required library/reference?

This is a DotNetCore 3.1 application.

Thanks!

**Comment by flipbit** [comment]
Hi, apologies, my bad - the README.md documentation was out of date.  I've updated it now for the 3.x release.

In the current version of the library, the `WhoisResponse` object returned from a query is already parsed.  You can just serialise it directly / access it's properties to get the various fields.

If you need to get the raw response returned from the server, you can access it via the `WhoisResponse.Content` property.

Thanks!

**Comment by SimonFletcher** [comment]
That’s brilliant.  Thank you, and thank you for replying so quickly.

-- 
Simon Fletcher
